#!/bin/bash

year=2020
if [ "$#" = "0" ]
then
    day=$(date +%-d)
    year=$(date +%Y)
else
    day=$1
    year=$2
    if [ "$year" == "" ]
    then
        year="2020"
    fi
fi
day0=$(echo $day | awk '{if (length($1)==1) printf("0%s",$1); else print $1;}')
out="$year/day${day0}.py"
data="$year/day${day0}.input"
touch "$year/day${day0}-test.input"

if [ -f $out -o -f $data ]
then
    echo "error: files already exist"
    echo " $out"
    echo " $data"
    exit 1
fi

if [ "$COOKIE" == "" ]
then
    echo "COOKIE environment variable is not set"
    echo "must be set to your the cookie: header when loading a valid input"
    exit 1 
fi

echo "writing template to $out"
cp template.py $out
sed -i "" "s|Day|Day${day0}|g" $out
sed -i "" "s|day|day${day0}|g" $out
chmod +x $out
echo "writing input to $data"
curl -s -H "cookie: $COOKIE" -o $data "https://adventofcode.com/${year}/day/${day}/input"
