#!/bin/bash

year=2020
if [ "$#" = "0" ]
then
    day=$(date +%-d)
    year=$(date +%Y)
else
    day=$1
    year=$2
    if [ "$year" == "" ]
    then
        year="2020"
    fi
fi
out="$year/day${day}.py"
data="$year/day${day}.input"
echo "writing template to $out"
cp template.py $out
sed -i "" "s|Day|Day${day}|g" $out
sed -i "" "s|day|day${day}|g" $out
chmod +x $out
echo "writing input to $data"
curl -s -H "cookie: $COOKIE" -o $data "https://adventofcode.com/${year}/day/${day}/input"
